# This file is a collection of all my bashrc settings

# history settings
#
# format
#
#export HISTTIMEFORMAT="%h %d %H:%M:%S "
#
# example
#   114  Jun 08 16:31:10 top
#   116  Jun 08 16:31:22 history
#
#
# number of command history & number of maxmium lines
export HISTSIZE=1000
export HISTFILESIZE=2000
#
#
# controller
#   ignorespace     don’t save lines which begin with a <space> character
#   ignoredups      don’t save lines matching the previous history entry
#   ignoreboth      use both ‘ignorespace’ and ‘ignoredups’
#   erasedups       eliminate duplicates across the whole history
export HISTCONTROL=ignorespace
#
#
# ignore commands
#
# ignore ls & ps
#export HISTIGNORE="ls:ps"
#
# don’t save commands start with s
#export HISTIGNORE="s*"
#
#
# change history file
#export HISTFILE=~/.my_file
#
#
# append hisotry rather than overwrite it
#shopt -s histappend



# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
#
#
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar



# make less more friendly for non-text input files, see lesspipe(1)
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"



# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi



# PS1
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '



# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" \
             "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'



# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]]; then
        . /usr/share/bash-completion/bash_completion
    elif [[ -f /etc/bash_completion ]]; then
        . /etc/bash_completion
    fi
fi


# xxz385 defined alias
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias vi=vim

alias ls='ls --color=auto'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'

alias grep='grep --color=auto'

# python server
alias python-server="python -m http.server 8000"


# rubygems
if which ruby >/dev/null && which gem >/dev/null; then
    export GEM_HOME="$(ruby -r rubygems -e 'puts Gem.user_dir')"
    PATH="$GEM_HOME/bin:$PATH"
fi


# pyenv
export PYENV_ROOT="$HOME/pyenv" 
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
#export PATH=/home/xiang/pyenv/versions/3.5.2/bin:$PATH
#export PATH=/home/xiang/pyenv/versions/3.8.2/bin:$PATH

# Gaussian_09
g09root="/home/xiang/Applications/G09.E01.AVX"
   GAUSS_SCRDIR="/home/xiang/Temp"
   export g09root GAUSS_SCRDIR
   . $g09root/g09/bsd/g09.profile

# BOSS
export BOSSdir="/home/xiang/Applications/BOSS/boss49-G09-IL"

# packmol
export PATH=/home/xiang/Applications/packmol-18.169/bin:$PATH

# Matlab
export PATH=/usr/local/MATLAB/R2016b/bin:$PATH

# define default editor
export EDITOR=gedit

# travis
export PATH=/home/xiang/Applications/travis-src-190101/exe:$PATH

# freeplane
alias freeplane=~/Applications/freeplane-1.7.7/freeplane.sh


alias visclean='for i in vis_*; do if [[ ! -f $i/vis.gro ]]; 
    then echo "<$i> remove everything"; rm -f $i/*; 
    else cd $i; echo "<$i> process"; 
    rm -f vis.cpt vis.log energy* \#energy* mdout*; 
    cd ../; fi; done'

alias prodclean='rm -f energy* \#energy* mdout* \#mdout* prod.{cpt,log};
    rm prod_prev.cpt surf.{cpt,log} surf_prev.cpt tmp* min* npt* *err *out prod_surf*'



# python server
alias python-server="python -m http.server 8000"


# rubygems
if which ruby >/dev/null && which gem >/dev/null; then
    export GEM_HOME="$(ruby -r rubygems -e 'puts Gem.user_dir')"
    PATH="$GEM_HOME/bin:$PATH"
fi



# For future convenience, here list all the installed useful packages
# date: March 4, 2020
#
#  1, Microsoft vscode (!Action: setting.json, shortcuts, extensions)
#  2, WPS
#  3, Foxit PDF
#  4, Matlab
#  5, Gaussian & GaussView (!Action: export PATH)
#  6, Eclipse
#  7, Flame (Screenshot)
#  8, CopyQ (ClipboardManager)
#  9, VMD
# 10, Freeplane (Mindtool)
# 11, Tweak (Gnome-tool)
# 12, dconf-editor (Gnome-tool)
# 13, GParted (DiskManager)
# 14, pyenv  (!Action: ChangeInIdleScript)
# 15, BOSS   (!Action: PATH) 
# 16, FileZilla
# 17, ssh & git   (Remote login & Serve setup)
# 18, gedit  (!Action: change windowSize, style, extension)
# 19, Sogou  (Fcitx)
# 20, dash-to-dock (!Action: Separate Workspace) 
# 21, Firefox & Chrome
# 22, GNU Image Manipulation Program (photoshop alike)
# 23, Drawio
# 24, Oracle Virtual Machine
# 25, GeoGebra
# 26, VLC Media Player



